# Generated by Django 4.1.2 on 2022-10-29 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_inventory_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 19, 0, 58, 327270)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 19, 0, 58, 327270)),
        ),
    ]
