# Generated by Django 4.1.2 on 2022-10-29 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_inventory_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 11, 30, 24, 707356)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 11, 30, 24, 732311)),
        ),
    ]
