# Generated by Django 4.1.2 on 2022-10-29 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_inventory_date_created_alter_inventory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='crud.supplier'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 16, 43, 21, 296286)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 16, 43, 21, 270529)),
        ),
        migrations.DeleteModel(
            name='LinkModel',
        ),
    ]
