# Generated by Django 4.1.2 on 2022-10-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_alter_inventory_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_created',
        ),
    ]
